Run python ./sec_form4_screener_reportlab_summary.py
Fetching current Form 4 filings via EDGAR Next API...
⚠️ SEC API non accessible (403 Client Error: Forbidden for url: https://efts.sec.gov/LATEST/search-index?keys=formType%3A%224%22&category=custom&forms=4&start=0&count=100&sortField=filedAt&sortOrder=desc), tentative fallback RSS...
❌ Error fetching RSS fallback: 403 Client Error: Forbidden for url: https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=4&count=100&output=atom
✅ 0 achats > 100 000 $ trouvés.
Generating PDF report...
✅ Rapport généré avec succès.
